// <auto-generated />
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace backend.Migrations
{
    [DbContext(typeof(BPressureContext))]
    [Migration("20200524063640_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.BPressure", b =>
                {
                    b.Property<int>("BPressureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dyastolic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DyastolicEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeanAraterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SleepStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Systolic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BPressureId");

                    b.ToTable("BPressures");
                });
#pragma warning restore 612, 618
        }
    }
}
